import { useState, useEffect } from "react";
import {
  Database,
  FileText,
  Loader2,
  CheckCircle2,
  AlertCircle,
  Copy,
  Trash2,
  Sparkles,
  ExternalLink,
  Zap,
  Search,
  RefreshCw,
  Plus,
  Eye,
  BookOpen,
  ArrowRight,
  HardDrive,
  Layers,
  FolderOpen,
  X,
  Download,
  CloudDownload,
  Check,
} from "lucide-react";

export interface DatasetCardItem {
  id: string;
  display_name: string;
  type: "local" | "collection" | "text_source" | "hub";
  domain: string;
  description: string;
  size_kb?: number;
  pairs_count?: string | number;
  chunks_count?: number;
  downloads?: number;
  likes?: number;
  hf_url?: string;
  is_local?: boolean;
  is_downloaded?: boolean;
  created_at?: number;
}

const HUB_RECOMMENDED_DATASETS: DatasetCardItem[] = [
  {
    id: "vishnusureshperumbavoor/vsp_alpaca",
    display_name: "VSP Persona & Portfolio (Alpaca)",
    type: "hub",
    domain: "Personal Identity & SFT",
    description: "Curated identity, tech stack, and personal portfolio dataset for Vishnu Suresh Perumbavoor. Formatted in standard Alpaca prompt-response pairs.",
    pairs_count: "Identity Alpaca Pairs",
    size_kb: 10,
    downloads: 12,
    likes: 5,
    hf_url: "https://huggingface.co/datasets/vishnusureshperumbavoor/vsp_alpaca",
  },
  {
    id: "lavita/MedQuAD",
    display_name: "MedQuAD (Medical QA)",
    type: "hub",
    domain: "Medical & Radiology",
    description: "47,457 medical question-answer pairs compiled from 12 NIH institutes. Ideal for clinical reasoning and diagnostic SLM fine-tuning.",
    pairs_count: "47.5k Q&A Pairs",
    size_kb: 32000,
    downloads: 85400,
    likes: 340,
    hf_url: "https://huggingface.co/datasets/lavita/MedQuAD",
  },
  {
    id: "yahma/alpaca-cleaned",
    display_name: "Alpaca Cleaned",
    type: "hub",
    domain: "General Instruct",
    description: "52,000 high-quality, sanitized instruction-following examples formatted in standard Alpaca prompt-response pairs.",
    pairs_count: "52k Pairs",
    size_kb: 44000,
    downloads: 245000,
    likes: 920,
    hf_url: "https://huggingface.co/datasets/yahma/alpaca-cleaned",
  },
  {
    id: "tatsu-lab/alpaca",
    display_name: "Stanford Alpaca",
    type: "hub",
    domain: "Multi-Task SFT",
    description: "The seminal 52k instruction-following dataset generated by OpenAI text-davinci-003 for instruction tuning.",
    pairs_count: "52k Pairs",
    size_kb: 43000,
    downloads: 480000,
    likes: 1350,
    hf_url: "https://huggingface.co/datasets/tatsu-lab/alpaca",
  },
  {
    id: "HuggingFaceH4/instruction-dataset",
    display_name: "H4 Multi-Turn Instruct",
    type: "hub",
    domain: "Conversational & Logic",
    description: "Curated multi-turn instruction dataset combining Anthropic HH, UltraFeedback, and Capybara for conversational alignment.",
    pairs_count: "120k Dialogs",
    size_kb: 95000,
    downloads: 160000,
    likes: 640,
    hf_url: "https://huggingface.co/datasets/HuggingFaceH4/instruction-dataset",
  },
  {
    id: "Open-Orca/OpenOrca",
    display_name: "OpenOrca Reasoning",
    type: "hub",
    domain: "Chain-of-Thought Reasoning",
    description: "Flan collection dataset enhanced with detailed step-by-step reasoning explanations to boost logical reasoning in SLMs.",
    pairs_count: "1M+ Steps",
    size_kb: 320000,
    downloads: 320000,
    likes: 1800,
    hf_url: "https://huggingface.co/datasets/Open-Orca/OpenOrca",
  },
  {
    id: "timdettmers/openassistant-guanaco",
    display_name: "Guanaco Assistant",
    type: "hub",
    domain: "Helpful & Honest Assistant",
    description: "Sub-sampled, high-quality multilingual assistant conversation pairs extracted from the OpenAssistant project.",
    pairs_count: "9.8k Pairs",
    size_kb: 12000,
    downloads: 195000,
    likes: 710,
    hf_url: "https://huggingface.co/datasets/timdettmers/openassistant-guanaco",
  },
];

export function KnowledgeLibrary({
  onDistillComplete,
  distillStatus,
  setDistillStatus,
  showDistillUI,
  setShowDistillUI,
}: {
  onDistillComplete?: (datasetId: string) => void;
  distillStatus: any;
  setDistillStatus: (s: any) => void;
  showDistillUI: boolean;
  setShowDistillUI: (v: boolean) => void;
}) {
  const [collections, setCollections] = useState<any[]>([]);
  const [localDatasets, setLocalDatasets] = useState<any[]>([]);
  const [textSources, setTextSources] = useState<any[]>([]);
  const [cachedMap, setCachedMap] = useState<Record<string, boolean>>({});
  const [downloadingId, setDownloadingId] = useState<string | null>(null);
  const [downloadProgressMap, setDownloadProgressMap] = useState<Record<string, { progress: number; task: string }>>({});
  const [isLoading, setIsLoading] = useState(false);
  const [searchQuery, setSearchQuery] = useState("");
  const [activeFilter, setActiveFilter] = useState<"all" | "local" | "collection" | "hub" | "text_source">("all");

  // Ingest / Harvest Modal State
  const [showIngestModal, setShowIngestModal] = useState(false);
  const [sourceType, setSourceType] = useState<"pdf" | "url" | "text" | "hub">("pdf");
  const [sourceInput, setSourceInput] = useState("");
  const [newCollectionName, setNewCollectionName] = useState("");
  const [isMining, setIsMining] = useState(false);
  const [statusMsg, setStatusMsg] = useState<{ text: string; type: "success" | "error" | "info" } | null>(null);

  // Preview Modal State
  const [previewDataset, setPreviewDataset] = useState<DatasetCardItem | null>(null);
  const [previewSamples, setPreviewSamples] = useState<any[]>([]);
  const [isLoadingPreview, setIsLoadingPreview] = useState(false);
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);

  // Distillation Modal State
  const [distillTarget, setDistillTarget] = useState<DatasetCardItem | null>(null);
  const [distillPersona, setDistillPersona] = useState("");

  // Deletion State
  const [itemToDelete, setItemToDelete] = useState<{ id: string; type: "local" | "collection" | "text_source"; name: string } | null>(null);
  const [isDeleting, setIsDeleting] = useState(false);

  const fetchAllData = async () => {
    setIsLoading(true);
    await Promise.all([fetchCollections(), fetchLocalDatasets(), fetchTextSources(), fetchCacheStatus()]);
    setIsLoading(false);
  };

  const fetchCacheStatus = async () => {
    try {
      const resp = await fetch("http://127.0.0.1:2000/dataset_cache_status");
      const data = await resp.json();
      if (data.cached_datasets) {
        setCachedMap(data.cached_datasets);
      }
    } catch (e) {
      console.error("Failed fetching cache status:", e);
    }
  };

  const handleDownloadDataset = async (datasetId: string) => {
    setDownloadingId(datasetId);
    setDownloadProgressMap((prev) => ({
      ...prev,
      [datasetId]: { progress: 10, task: "Starting download..." },
    }));

    try {
      await fetch("http://127.0.0.1:2000/download_hf_dataset", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ dataset_id: datasetId }),
      });

      const pollInterval = setInterval(async () => {
        try {
          const pRes = await fetch(
            `http://127.0.0.1:2000/dataset_download_progress?id=${encodeURIComponent(datasetId)}`
          );
          const pData = await pRes.json();
          if (pData.progress !== undefined) {
            setDownloadProgressMap((prev) => ({
              ...prev,
              [datasetId]: { progress: pData.progress, task: pData.task || "Downloading..." },
            }));
          }
          if (pData.status === "completed" || pData.progress >= 100) {
            clearInterval(pollInterval);
            setCachedMap((prev) => ({ ...prev, [datasetId]: true }));
            setDownloadingId(null);
          } else if (pData.status === "error") {
            clearInterval(pollInterval);
            setDownloadingId(null);
          }
        } catch (err) {
          clearInterval(pollInterval);
          setDownloadingId(null);
        }
      }, 500);
    } catch (e) {
      console.error("Failed downloading dataset:", e);
      setDownloadingId(null);
    }
  };

  const fetchCollections = async () => {
    try {
      const resp = await fetch("http://127.0.0.1:3001/mcp/call", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name: "list_knowledge_collections",
          arguments: {},
        }),
      });
      const data = await resp.json();
      const text = data[0]?.text || data.result?.[0]?.text || "";
      if (text.includes("[JSON_RESULTS]")) {
        const jsonStr = text.split("[JSON_RESULTS]")[1].trim();
        const results = JSON.parse(jsonStr);
        setCollections(results.collections || []);
      }
    } catch (e) {
      console.error("Failed to fetch collections:", e);
    }
  };

  const fetchLocalDatasets = async () => {
    try {
      const resp = await fetch("http://127.0.0.1:2000/list_local_datasets");
      const data = await resp.json();
      setLocalDatasets(data.datasets || []);
    } catch (e) {
      console.error("Failed to fetch local datasets:", e);
    }
  };

  const fetchTextSources = async () => {
    try {
      const resp = await fetch("http://127.0.0.1:2000/text_sources");
      const data = await resp.json();
      setTextSources(data.sources || []);
    } catch (e) {
      console.error("Failed to fetch text sources:", e);
    }
  };

  useEffect(() => {
    fetchAllData();

    // Check background distill status
    const checkStatus = async () => {
      try {
        const resp = await fetch("http://127.0.0.1:2000/distill/status");
        const status = await resp.json();
        if (status.step !== "idle") {
          setDistillStatus(status);
          setShowDistillUI(true);
        }
      } catch (e) {
        console.error("Failed to fetch initial distill status:", e);
      }
    };
    checkStatus();
  }, []);

  // Build Unified Dataset Cards
  const allDatasetCards: DatasetCardItem[] = [
    // 1. Local Distilled JSONL Datasets
    ...localDatasets.map((d: any) => ({
      id: d.id,
      display_name: d.display_name || d.id.replace(".jsonl", ""),
      type: "local" as const,
      domain: "Distilled Alpaca JSONL",
      description: `Locally harvested fine-tuning dataset formatted in standard instruction-input-response pairs. Ready for immediate SFT.`,
      size_kb: d.size_kb || 0,
      pairs_count: "Local JSONL",
      is_local: true,
      is_downloaded: true,
      hf_url: d.hf_url,
    })),

    // 2. ChromaDB Knowledge Collections (Vector Databases)
    ...collections.map((c: any) => ({
      id: c.name,
      display_name: c.name,
      type: "collection" as const,
      domain: "Vector Knowledge Base",
      description: `Vectorized knowledge store indexed in local ChromaDB. Can be explored, queried semantically, or distilled into Alpaca training pairs.`,
      chunks_count: c.count || 0,
      pairs_count: `${c.count || 0} Vector Chunks`,
      size_kb: Math.round((c.count || 0) * 1.5),
      is_downloaded: true,
    })),

    // 3. Pasted Text Sources
    ...textSources.map((s: any) => ({
      id: s.id,
      display_name: s.display_name || s.id,
      type: "text_source" as const,
      domain: "Raw Text Source",
      description: `Saved raw reference text (${s.char_count || 0} chars). Can be distilled into specialized training pairs.`,
      size_kb: Math.round((s.char_count || 0) / 1024),
      pairs_count: `${s.char_count || 0} Characters`,
      is_downloaded: true,
    })),

    // 4. Hugging Face Recommended Datasets
    ...HUB_RECOMMENDED_DATASETS.map((hubDs) => ({
      ...hubDs,
      is_downloaded: !!cachedMap[hubDs.id],
    })),
  ];

  // Filtering
  const filteredDatasets = allDatasetCards.filter((card) => {
    const matchesFilter = activeFilter === "all" || card.type === activeFilter;
    const query = searchQuery.toLowerCase().trim();
    const matchesQuery =
      !query ||
      card.id.toLowerCase().includes(query) ||
      card.display_name.toLowerCase().includes(query) ||
      card.domain.toLowerCase().includes(query) ||
      card.description.toLowerCase().includes(query);
    return matchesFilter && matchesQuery;
  });

  const locallyDownloadedCount = allDatasetCards.filter((d) => d.is_downloaded).length;
  const hubCachedCount = allDatasetCards.filter((d) => d.type === "hub" && d.is_downloaded).length;
  const totalLocalCount = localDatasets.length;
  const totalCollectionsCount = collections.length;
  const totalHubCount = HUB_RECOMMENDED_DATASETS.length;

  // Handle Dataset Preview
  const handleOpenPreview = async (dataset: DatasetCardItem) => {
    setPreviewDataset(dataset);
    setPreviewSamples([]);
    setIsLoadingPreview(true);

    if (dataset.type === "collection") {
      try {
        const resp = await fetch("http://127.0.0.1:3001/mcp/call", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            name: "explore_knowledge_collection",
            arguments: { collection: dataset.id, limit: 10 },
          }),
        });
        const data = await resp.json();
        const text = data.error || data[0]?.text || data.result?.[0]?.text || "";
        if (text.includes("[JSON_RESULTS]")) {
          const results = JSON.parse(text.split("[JSON_RESULTS]")[1].trim());
          setPreviewSamples(results || []);
        }
      } catch (e) {
        console.error("Failed exploring collection:", e);
      } finally {
        setIsLoadingPreview(false);
      }
      return;
    }

    try {
      const resp = await fetch(`http://127.0.0.1:2000/preview_dataset?id=${encodeURIComponent(dataset.id)}`);
      const data = await resp.json();
      if (data.samples && data.samples.length > 0) {
        setPreviewSamples(data.samples);
      } else {
        setPreviewSamples([]);
      }
    } catch (e) {
      console.error("Failed previewing dataset:", e);
      setPreviewSamples([]);
    } finally {
      setIsLoadingPreview(false);
    }
  };

  // Handle Ingest / Harvest
  const handleIngest = async () => {
    const collection = newCollectionName.trim() || "my-knowledge";
    if (!sourceInput.trim()) {
      setStatusMsg({ text: "Please enter a valid file path, URL, or pasted text.", type: "error" });
      return;
    }

    if (sourceType === "text") {
      try {
        setIsMining(true);
        const resp = await fetch("http://127.0.0.1:2000/text_sources", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ raw_text: sourceInput, name: collection }),
        });
        const data = await resp.json();
        if (!resp.ok) throw new Error(data.detail || "Failed saving text source.");
        setStatusMsg({ text: `✅ Saved raw text source '${data.source?.display_name}'.`, type: "success" });
        setSourceInput("");
        setNewCollectionName("");
        await fetchTextSources();
        setTimeout(() => {
          setShowIngestModal(false);
          setStatusMsg(null);
        }, 1200);
      } catch (e: any) {
        setStatusMsg({ text: e.message || "Failed saving text source.", type: "error" });
      } finally {
        setIsMining(false);
      }
      return;
    }

    // PDF or Web URL Ingestion via Vector MCP
    setIsMining(true);
    setStatusMsg(null);
    try {
      const resp = await fetch("http://127.0.0.1:3001/mcp/call", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name: "ingest_knowledge",
          arguments: { source: sourceInput, collection: collection },
        }),
      });
      const data = await resp.json();
      const text = data.error || data[0]?.text || data.result?.[0]?.text || "";
      if (text.includes("[JSON_RESULTS]")) {
        const jsonStr = text.split("[JSON_RESULTS]")[1].trim();
        const stats = JSON.parse(jsonStr);
        setStatusMsg({
          text: `✅ Harvest Complete: ${stats.report?.chunks || 0} chunks indexed into '${collection}'.`,
          type: "success",
        });
        setSourceInput("");
        setNewCollectionName("");
        await fetchCollections();
        setTimeout(() => {
          setShowIngestModal(false);
          setStatusMsg(null);
        }, 1500);
      } else {
        setStatusMsg({ text: text || "Ingestion error occurred.", type: "error" });
      }
    } catch (e: any) {
      setStatusMsg({ text: e.message || "Ingestion pipeline interrupted.", type: "error" });
    } finally {
      setIsMining(false);
    }
  };

  // Browse PDF File
  const handleBrowsePdf = async () => {
    try {
      const resp = await fetch("http://127.0.0.1:2000/browse_pdf");
      const data = await resp.json();
      if (data.path) {
        setSourceInput(data.path);
        if (!newCollectionName) {
          const base = data.path.split(/[\\/]/).pop()?.split(".")[0];
          if (base) setNewCollectionName(base + "-docs");
        }
      }
    } catch (e) {
      console.error("Browse failed:", e);
    }
  };

  // Start Distillation
  const handleStartDistill = async () => {
    if (!distillTarget) return;
    setShowDistillUI(true);
    setDistillStatus({
      step: "init",
      progress: 5,
      current_task: `Distilling ${distillTarget.display_name} into Alpaca format...`,
    });

    try {
      if (distillTarget.type === "collection") {
        await fetch("http://127.0.0.1:2000/distill/start", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            collection_name: distillTarget.id,
            auto_deploy: false,
            persona: distillPersona,
          }),
        });
      } else if (distillTarget.type === "text_source") {
        const sourceResp = await fetch(`http://127.0.0.1:2000/text_sources/${distillTarget.id}`);
        const sourceData = await sourceResp.json();
        await fetch("http://127.0.0.1:2000/distill/text", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            raw_text: sourceData.raw_text,
            dataset_name: distillTarget.display_name || distillTarget.id,
            auto_deploy: false,
            persona: distillPersona,
            target_pairs: 100,
          }),
        });
      }
      setDistillTarget(null);
      // Poll until complete
      const interval = setInterval(async () => {
        await fetchLocalDatasets();
        const res = await fetch("http://127.0.0.1:2000/distill/status");
        const status = await res.json();
        if (status.step === "complete" || status.step === "error") {
          clearInterval(interval);
          await fetchLocalDatasets();
        }
      }, 3000);
    } catch (e: any) {
      setDistillStatus({ step: "error", progress: 0, current_task: e.message });
    }
  };

  // Delete Item
  const handleExecuteDelete = async () => {
    if (!itemToDelete) return;
    setIsDeleting(true);
    try {
      if (itemToDelete.type === "collection") {
        await fetch("http://127.0.0.1:3001/mcp/call", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            name: "delete_knowledge_collection",
            arguments: { collection: itemToDelete.id },
          }),
        });
      } else if (itemToDelete.type === "local") {
        await fetch("http://127.0.0.1:2000/delete_dataset", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ id: itemToDelete.id }),
        });
      } else if (itemToDelete.type === "text_source") {
        await fetch(`http://127.0.0.1:2000/text_sources/${itemToDelete.id}`, { method: "DELETE" });
      }
      setItemToDelete(null);
      await fetchAllData();
    } catch (e) {
      console.error("Delete failed:", e);
    } finally {
      setIsDeleting(false);
    }
  };

  return (
    <div className="flex-1 flex flex-col bg-[#0B090F] overflow-y-auto p-6 md:p-8 space-y-8 w-full animate-in fade-in duration-500">
      <div className="max-w-7xl mx-auto w-full space-y-6">
        {/* Top Header Banner */}
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-white/5 pb-6">
          <div>
            <h2 className="text-2xl md:text-3xl font-black text-white tracking-tight flex items-center gap-3">
              <Database className="text-indigo-400" size={28} />
              <span>Datasets Library</span>
            </h2>
            <p className="text-sm text-white/40 mt-1">
              Explore, harvest, mine, and distill instruction datasets for local SLM post-training.
            </p>
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={fetchAllData}
              disabled={isLoading}
              className="flex items-center gap-2 px-3.5 py-2 rounded-xl bg-white/5 hover:bg-white/10 text-white/70 hover:text-white border border-white/10 text-xs font-bold transition-all cursor-pointer"
              title="Refresh Datasets"
            >
              <RefreshCw size={14} className={isLoading ? "animate-spin" : ""} />
              <span>Refresh</span>
            </button>

            <button
              onClick={() => setShowIngestModal(true)}
              className="flex items-center gap-2 px-4 py-2 rounded-xl bg-gradient-to-r from-indigo-500 to-purple-600 hover:from-indigo-400 hover:to-purple-500 text-white font-bold text-xs transition-all shadow-lg shadow-indigo-900/20 cursor-pointer"
            >
              <Plus size={14} />
              <span>Harvest / Ingest Source</span>
            </button>
          </div>
        </div>

        {/* Live Distillation Active Banner */}
        {showDistillUI && distillStatus && distillStatus.step !== "idle" && (
          <div className="p-4 rounded-2xl bg-[#140F1D] border border-purple-500/30 shadow-lg shadow-purple-500/10 space-y-3 animate-in fade-in duration-300">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Sparkles size={16} className="text-purple-400 animate-pulse" />
                <span className="text-xs font-bold text-white tracking-wide">
                  Alpaca Distillation Agent Active
                </span>
              </div>
              <button
                onClick={() => setShowDistillUI(false)}
                className="text-white/40 hover:text-white text-xs cursor-pointer"
              >
                Dismiss
              </button>
            </div>
            <p className="text-xs text-purple-200 font-mono">
              {distillStatus.current_task || "Distilling knowledge base..."}
            </p>
            <div className="w-full bg-white/5 h-2 rounded-full overflow-hidden">
              <div
                className="bg-purple-500 h-full transition-all duration-300 rounded-full"
                style={{ width: `${distillStatus.progress || 0}%` }}
              />
            </div>
          </div>
        )}

        {/* Telemetry & Stats Cards */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
          <div className="p-4 rounded-2xl bg-[#140F1D] border border-white/5 space-y-1">
            <span className="text-[11px] text-white/40 font-bold uppercase tracking-wider">
              Total Downloaded
            </span>
            <div className="text-2xl font-black text-white font-mono">{locallyDownloadedCount}</div>
          </div>
          <div className="p-4 rounded-2xl bg-[#140F1D] border border-white/5 space-y-1">
            <span className="text-[11px] text-emerald-400/80 font-bold uppercase tracking-wider">
              Local SFT JSONL
            </span>
            <div className="text-2xl font-black text-emerald-400 font-mono">{totalLocalCount}</div>
          </div>
          <div className="p-4 rounded-2xl bg-[#140F1D] border border-white/5 space-y-1">
            <span className="text-[11px] text-purple-400/80 font-bold uppercase tracking-wider">
              Vector Collections
            </span>
            <div className="text-2xl font-black text-purple-400 font-mono">{totalCollectionsCount}</div>
          </div>
          <div className="p-4 rounded-2xl bg-[#140F1D] border border-white/5 space-y-1">
            <span className="text-[11px] text-indigo-400/80 font-bold uppercase tracking-wider">
              Hub Cached / Ready
            </span>
            <div className="text-2xl font-black text-indigo-400 font-mono">{hubCachedCount}</div>
          </div>
        </div>

        {/* Search Bar & Filters */}
        <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-3 pt-2">
          {/* Filter Pills */}
          <div className="flex items-center gap-1.5 p-1 bg-[#140F1D] rounded-xl border border-white/5 overflow-x-auto">
            {[
              { key: "all", label: `All Datasets (${locallyDownloadedCount})` },
              { key: "local", label: `Local JSONL (${totalLocalCount})` },
              { key: "collection", label: `Vector Collections (${totalCollectionsCount})` },
              { key: "hub", label: `Hub Recommended (${totalHubCount})` },
              { key: "text_source", label: `Pasted Text (${textSources.length})` },
            ].map((tab) => (
              <button
                key={tab.key}
                onClick={() => setActiveFilter(tab.key as any)}
                className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all whitespace-nowrap cursor-pointer ${activeFilter === tab.key
                  ? "bg-indigo-500/20 text-indigo-300 border border-indigo-500/30"
                  : "text-white/40 hover:text-white hover:bg-white/5"
                  }`}
              >
                {tab.label}
              </button>
            ))}
          </div>

          {/* Search Input */}
          <div className="relative w-full sm:w-80">
            <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 text-white/30" size={14} />
            <input
              type="text"
              placeholder="Search datasets, instructions, domains..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full bg-[#140F1D] border border-white/5 rounded-xl pl-9 pr-4 py-2 text-xs text-white placeholder-white/20 focus:outline-none focus:border-indigo-500/50 transition-all"
            />
          </div>
        </div>

        {/* Dataset Card Grid */}
        {filteredDatasets.length === 0 ? (
          <div className="text-center py-16 px-4 rounded-3xl border border-dashed border-white/5 bg-[#140F1D]/50">
            <Database className="mx-auto text-white/20 mb-3" size={36} />
            <h3 className="text-base font-bold text-white/70">No matching datasets found</h3>
            <p className="text-xs text-white/30 mt-1 max-w-sm mx-auto">
              Try adjusting your search query or harvest a new knowledge base from documents or web URLs.
            </p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
            {filteredDatasets.map((dataset) => {
              const isLocal = dataset.type === "local";
              const isCollection = dataset.type === "collection";
              const isHub = dataset.type === "hub";
              const isTextSource = dataset.type === "text_source";

              return (
                <div
                  key={dataset.id}
                  className={`group relative rounded-2xl bg-[#140F1D] border transition-all duration-300 flex flex-col justify-between overflow-hidden shadow-xl ${isLocal
                    ? "border-emerald-500/20 hover:border-emerald-500/50 hover:shadow-emerald-500/5"
                    : isCollection
                      ? "border-purple-500/20 hover:border-purple-500/50 hover:shadow-purple-500/5"
                      : isTextSource
                        ? "border-amber-500/20 hover:border-amber-500/50 hover:shadow-amber-500/5"
                        : "border-indigo-500/20 hover:border-indigo-500/50 hover:shadow-indigo-500/5"
                    }`}
                >
                  <div className="p-5 space-y-4">
                    {/* Card Top: Icon & Badge */}
                    <div className="flex items-start justify-between gap-3">
                      <div className="flex items-center gap-3">
                        <div
                          className={`w-10 h-10 rounded-xl flex items-center justify-center shrink-0 ${isLocal
                            ? "bg-emerald-500/10 text-emerald-400 border border-emerald-500/20"
                            : isCollection
                              ? "bg-purple-500/10 text-purple-400 border border-purple-500/20"
                              : isTextSource
                                ? "bg-amber-500/10 text-amber-400 border border-amber-500/20"
                                : "bg-indigo-500/10 text-indigo-400 border border-indigo-500/20"
                            }`}
                        >
                          {isLocal ? (
                            <Zap size={20} />
                          ) : isCollection ? (
                            <Layers size={20} />
                          ) : isTextSource ? (
                            <FileText size={20} />
                          ) : (
                            <Database size={20} />
                          )}
                        </div>

                        <div className="space-y-0.5">
                          <h3
                            className="text-sm font-bold text-white tracking-tight group-hover:text-indigo-300 transition-colors line-clamp-1"
                            title={dataset.display_name}
                          >
                            {dataset.display_name}
                          </h3>
                          <span className="text-[10px] font-mono text-white/40 block truncate max-w-[190px]">
                            {dataset.id}
                          </span>
                        </div>
                      </div>

                      {/* Type & Download Status Badges */}
                      <div className="flex flex-col items-end gap-1">
                        <span
                          className={`text-[9px] font-bold px-2 py-0.5 rounded-full border whitespace-nowrap ${isLocal
                              ? "bg-emerald-500/10 text-emerald-300 border-emerald-500/20"
                              : isCollection
                                ? "bg-purple-500/10 text-purple-300 border-purple-500/20"
                                : isTextSource
                                  ? "bg-amber-500/10 text-amber-300 border-amber-500/20"
                                  : "bg-indigo-500/10 text-indigo-300 border-indigo-500/20"
                            }`}
                        >
                          {isLocal
                            ? "⚡ SFT Ready"
                            : isCollection
                              ? "📚 Vector DB"
                              : isTextSource
                                ? "✍️ Pasted Text"
                                : "🌐 HF Hub"}
                        </span>

                        {dataset.is_downloaded ? (
                          <span className="text-[8px] font-bold font-mono px-1.5 py-0.5 rounded bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 flex items-center gap-1">
                            <Check size={9} />
                            <span>Downloaded</span>
                          </span>
                        ) : (
                          <span className="text-[8px] font-bold font-mono px-1.5 py-0.5 rounded bg-amber-500/10 text-amber-400 border border-amber-500/20 flex items-center gap-1 animate-pulse">
                            <CloudDownload size={9} />
                            <span>Not Downloaded</span>
                          </span>
                        )}
                      </div>
                    </div>

                    {/* Domain Category Pill */}
                    <div className="flex items-center gap-2">
                      <span className="text-[10px] px-2 py-0.5 rounded bg-white/5 text-white/60 font-medium border border-white/5">
                        {dataset.domain}
                      </span>
                      {dataset.pairs_count && (
                        <span className="text-[10px] font-mono text-white/40">
                          {dataset.pairs_count}
                        </span>
                      )}
                    </div>

                    {/* Description */}
                    <p className="text-xs text-white/50 line-clamp-2 leading-relaxed">
                      {dataset.description}
                    </p>

                    {/* Telemetry Strip */}
                    <div className="pt-2 border-t border-white/5 flex items-center justify-between text-[11px] font-mono text-white/40">
                      {dataset.size_kb !== undefined && dataset.size_kb > 0 && (
                        <div className="flex items-center gap-1.5">
                          <HardDrive size={12} className="text-white/30" />
                          <span>
                            {dataset.size_kb > 1024
                              ? `${(dataset.size_kb / 1024).toFixed(1)} MB`
                              : `${dataset.size_kb} KB`}
                          </span>
                        </div>
                      )}

                      {dataset.downloads !== undefined && (
                        <span className="text-white/40 font-mono">
                          {dataset.downloads.toLocaleString()} DLs
                        </span>
                      )}

                      {dataset.hf_url && (
                        <a
                          href={dataset.hf_url}
                          target="_blank"
                          rel="noreferrer"
                          className="flex items-center gap-1 text-indigo-400/70 hover:text-indigo-300 text-[10px] hover:underline"
                        >
                          <span>HF Hub</span>
                          <ExternalLink size={10} />
                        </a>
                      )}
                    </div>
                  </div>

                  {/* Card Actions Bottom Strip */}
                  <div className="px-5 py-3.5 bg-[#0D0B14] border-t border-white/5 flex items-center justify-between gap-2">
                    <div className="flex items-center gap-2">
                      {/* Download Button / Progress Bar (Visible if dataset is not downloaded locally) */}
                      {!dataset.is_downloaded && (
                        downloadingId === dataset.id ? (
                          <div className="flex flex-col gap-1 px-3 py-1.5 rounded-xl bg-amber-500/10 border border-amber-500/30 min-w-[130px] animate-in fade-in duration-200">
                            <div className="flex items-center justify-between text-[9px] font-mono text-amber-300 font-bold">
                              <span className="truncate max-w-[85px]">{downloadProgressMap[dataset.id]?.task || "Downloading..."}</span>
                              <span>{downloadProgressMap[dataset.id]?.progress || 10}%</span>
                            </div>
                            <div className="w-full bg-white/10 h-1.5 rounded-full overflow-hidden">
                              <div
                                className="bg-amber-400 h-full transition-all duration-300 rounded-full"
                                style={{ width: `${downloadProgressMap[dataset.id]?.progress || 10}%` }}
                              />
                            </div>
                          </div>
                        ) : (
                          <button
                            onClick={(e) => {
                              e.stopPropagation();
                              handleDownloadDataset(dataset.id);
                            }}
                            className="px-3 py-1.5 rounded-xl bg-amber-500/10 hover:bg-amber-500/20 text-amber-300 hover:text-amber-200 border border-amber-500/30 text-xs font-semibold flex items-center gap-1.5 transition-all cursor-pointer shadow-sm"
                            title="Download & cache dataset locally for offline training"
                          >
                            <Download size={13} />
                            <span>Download</span>
                          </button>
                        )
                      )}

                      {/* Sample Preview Button */}
                      <button
                        onClick={() => handleOpenPreview(dataset)}
                        className="px-3 py-1.5 rounded-xl bg-white/5 hover:bg-white/10 text-white/70 hover:text-white text-xs font-semibold flex items-center gap-1.5 transition-all cursor-pointer"
                        title="Explore sample prompts & responses"
                      >
                        <Eye size={13} />
                        <span>Preview</span>
                      </button>

                      {/* Distill into Alpaca (for collections / text) */}
                      {(isCollection || isTextSource) && (
                        <button
                          onClick={() => setDistillTarget(dataset)}
                          className="px-3 py-1.5 rounded-xl bg-purple-500/10 hover:bg-purple-500/20 text-purple-300 hover:text-purple-200 border border-purple-500/20 text-xs font-semibold flex items-center gap-1.5 transition-all cursor-pointer"
                          title="Distill into Alpaca JSONL dataset"
                        >
                          <Sparkles size={13} />
                          <span>Distill</span>
                        </button>
                      )}

                      {/* Delete button (for local / collection) */}
                      {!isHub && (
                        <button
                          onClick={() => setItemToDelete({ id: dataset.id, type: dataset.type as any, name: dataset.display_name })}
                          className="p-1.5 rounded-xl text-white/30 hover:text-rose-400 hover:bg-rose-500/10 transition-all cursor-pointer"
                          title="Delete Dataset"
                        >
                          <Trash2 size={14} />
                        </button>
                      )}
                    </div>

                    {/* Main Action: Fine-Tune with this Dataset */}
                    <button
                      onClick={() => onDistillComplete?.(dataset.id)}
                      className="px-3.5 py-1.5 rounded-xl bg-indigo-500/20 hover:bg-indigo-500 text-indigo-200 hover:text-white border border-indigo-500/30 text-xs font-bold flex items-center gap-1.5 transition-all cursor-pointer group-hover:bg-indigo-600 group-hover:text-white"
                      title="Select dataset and jump to Build tab"
                    >
                      <Zap size={13} />
                      <span>Fine-Tune</span>
                      <ArrowRight size={12} className="group-hover:translate-x-0.5 transition-transform" />
                    </button>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>

      {/* ------------------------------------------------------------- */}
      {/* MODAL 1: Ingest & Harvest Knowledge Source */}
      {/* ------------------------------------------------------------- */}
      {showIngestModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-in fade-in duration-200">
          <div className="w-full max-w-xl bg-[#140F1D] border border-purple-500/20 rounded-3xl p-6 md:p-8 space-y-6 shadow-2xl relative">
            <div className="flex items-center justify-between border-b border-white/5 pb-4">
              <div className="flex items-center gap-2.5">
                <Database size={20} className="text-indigo-400" />
                <h3 className="text-lg font-bold text-white">Harvest New Dataset Source</h3>
              </div>
              <button
                onClick={() => setShowIngestModal(false)}
                className="p-1 text-white/40 hover:text-white rounded-lg hover:bg-white/5 transition-all"
              >
                <X size={18} />
              </button>
            </div>

            {/* Source Type Switcher */}
            <div className="grid grid-cols-3 gap-2 p-1 bg-[#0B090F] rounded-xl border border-white/5">
              {[
                { type: "pdf", label: "📄 PDF Document" },
                { type: "url", label: "🌐 Web URL" },
                { type: "text", label: "✍️ Paste Text" },
              ].map((tab) => (
                <button
                  key={tab.type}
                  type="button"
                  onClick={() => {
                    setSourceType(tab.type as any);
                    setSourceInput("");
                  }}
                  className={`py-2 rounded-lg text-xs font-bold transition-all cursor-pointer ${sourceType === tab.type
                    ? "bg-indigo-500/20 text-indigo-200 border border-indigo-500/30"
                    : "text-white/40 hover:text-white"
                    }`}
                >
                  {tab.label}
                </button>
              ))}
            </div>

            {/* Inputs */}
            <div className="space-y-4">
              <div>
                <label className="text-[10px] font-bold text-white/40 uppercase tracking-widest block mb-1.5">
                  Dataset / Collection Name
                </label>
                <input
                  type="text"
                  placeholder="e.g. radiology-reports-2026"
                  value={newCollectionName}
                  onChange={(e) => setNewCollectionName(e.target.value)}
                  className="w-full bg-[#0B090F] border border-white/10 rounded-xl px-4 py-2.5 text-xs text-white placeholder-white/20 focus:outline-none focus:border-indigo-500"
                />
              </div>

              <div>
                <label className="text-[10px] font-bold text-white/40 uppercase tracking-widest block mb-1.5">
                  {sourceType === "pdf"
                    ? "Local PDF Document Path"
                    : sourceType === "url"
                      ? "Web Page / Documentation URL"
                      : "Paste Source Text Content"}
                </label>

                {sourceType === "text" ? (
                  <textarea
                    rows={6}
                    placeholder="Paste medical literature, guidelines, or raw context here..."
                    value={sourceInput}
                    onChange={(e) => setSourceInput(e.target.value)}
                    className="w-full bg-[#0B090F] border border-white/10 rounded-xl p-4 text-xs text-white placeholder-white/20 focus:outline-none focus:border-indigo-500 resize-none font-mono"
                  />
                ) : (
                  <div className="flex items-center gap-2">
                    <input
                      type="text"
                      placeholder={
                        sourceType === "pdf"
                          ? "/path/to/clinical-report.pdf"
                          : "https://example.com/medical-guidelines"
                      }
                      value={sourceInput}
                      onChange={(e) => setSourceInput(e.target.value)}
                      className="flex-1 bg-[#0B090F] border border-white/10 rounded-xl px-4 py-2.5 text-xs text-white placeholder-white/20 focus:outline-none focus:border-indigo-500"
                    />
                    {sourceType === "pdf" && (
                      <button
                        type="button"
                        onClick={handleBrowsePdf}
                        className="px-4 py-2.5 rounded-xl bg-white/5 hover:bg-white/10 text-white text-xs font-bold border border-white/10 transition-all cursor-pointer flex items-center gap-1.5"
                      >
                        <FolderOpen size={14} />
                        <span>Browse</span>
                      </button>
                    )}
                  </div>
                )}
              </div>
            </div>

            {statusMsg && (
              <div
                className={`p-3 rounded-xl text-xs font-medium ${statusMsg.type === "success"
                  ? "bg-emerald-500/10 text-emerald-300 border border-emerald-500/20"
                  : "bg-rose-500/10 text-rose-300 border border-rose-500/20"
                  }`}
              >
                {statusMsg.text}
              </div>
            )}

            <div className="flex items-center justify-end gap-3 pt-2">
              <button
                type="button"
                onClick={() => setShowIngestModal(false)}
                className="px-4 py-2.5 rounded-xl text-xs font-bold text-white/50 hover:text-white"
              >
                Cancel
              </button>

              <button
                type="button"
                disabled={isMining || !sourceInput.trim()}
                onClick={handleIngest}
                className="px-6 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-bold text-xs transition-all shadow-lg shadow-indigo-900/30 flex items-center gap-2 cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {isMining ? <Loader2 size={14} className="animate-spin" /> : <Sparkles size={14} />}
                <span>{isMining ? "Indexing..." : "Start Harvesting"}</span>
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ------------------------------------------------------------- */}
      {/* MODAL 2: Dataset Sample Preview */}
      {/* ------------------------------------------------------------- */}
      {previewDataset && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-in fade-in duration-200">
          <div className="w-full max-w-3xl bg-[#140F1D] border border-white/10 rounded-3xl p-6 md:p-8 space-y-6 shadow-2xl flex flex-col max-h-[85vh]">
            <div className="flex items-center justify-between border-b border-white/5 pb-4 shrink-0">
              <div className="flex items-center gap-3">
                <BookOpen size={22} className="text-indigo-400" />
                <div>
                  <h3 className="text-base font-bold text-white">
                    Sample Data: {previewDataset.display_name}
                  </h3>
                  <span className="text-[10px] text-white/40 font-mono">
                    {previewDataset.id} • {previewDataset.domain}
                  </span>
                </div>
              </div>
              <button
                onClick={() => setPreviewDataset(null)}
                className="p-1.5 text-white/40 hover:text-white rounded-lg hover:bg-white/5 transition-all"
              >
                <X size={18} />
              </button>
            </div>

            {/* Content Area */}
            <div className="flex-1 overflow-y-auto space-y-4 pr-1">
              {isLoadingPreview ? (
                <div className="py-20 flex flex-col items-center justify-center gap-3 text-white/40 text-xs font-mono">
                  <Loader2 className="animate-spin text-indigo-400" size={24} />
                  <span>Loading dataset sample records...</span>
                </div>
              ) : previewSamples.length === 0 ? (
                <div className="py-16 text-center text-white/30 text-xs font-mono">
                  No sample records available for this dataset preview.
                </div>
              ) : (
                previewSamples.map((sample, idx) => {
                  const instruction =
                    sample.instruction ||
                    sample.question ||
                    sample.prompt ||
                    sample.query ||
                    sample.text ||
                    "";
                  const input = sample.input || "";
                  const response =
                    sample.response ||
                    sample.answer ||
                    sample.output ||
                    sample.target ||
                    (typeof sample === "string" ? sample : JSON.stringify(sample, null, 2));

                  return (
                    <div
                      key={idx}
                      className="p-4 rounded-2xl bg-[#0B090F] border border-white/5 space-y-3 relative group"
                    >
                      <div className="flex items-center justify-between">
                        <span className="text-[10px] font-bold text-indigo-400 uppercase tracking-wider font-mono">
                          Record #{idx + 1}
                        </span>
                        <button
                          onClick={() => {
                            navigator.clipboard.writeText(
                              JSON.stringify({ instruction, input, response }, null, 2)
                            );
                            setCopiedIndex(idx);
                            setTimeout(() => setCopiedIndex(null), 2000);
                          }}
                          className="text-white/30 hover:text-white text-[10px] flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity"
                        >
                          {copiedIndex === idx ? (
                            <CheckCircle2 size={12} className="text-emerald-400" />
                          ) : (
                            <Copy size={12} />
                          )}
                          <span>{copiedIndex === idx ? "Copied" : "Copy JSON"}</span>
                        </button>
                      </div>

                      {instruction && (
                        <div className="space-y-1">
                          <span className="text-[9px] font-bold text-amber-400/80 uppercase tracking-widest font-mono">
                            Instruction
                          </span>
                          <p className="text-xs text-white/80 leading-relaxed font-sans">{instruction}</p>
                        </div>
                      )}

                      {input && (
                        <div className="space-y-1">
                          <span className="text-[9px] font-bold text-purple-400/80 uppercase tracking-widest font-mono">
                            Input Context
                          </span>
                          <p className="text-xs text-white/60 leading-relaxed font-sans">{input}</p>
                        </div>
                      )}

                      {response && (
                        <div className="space-y-1">
                          <span className="text-[9px] font-bold text-emerald-400/80 uppercase tracking-widest font-mono">
                            Response
                          </span>
                          <p className="text-xs text-white/70 leading-relaxed font-sans bg-white/5 p-2.5 rounded-xl border border-white/5 whitespace-pre-wrap">
                            {response}
                          </p>
                        </div>
                      )}
                    </div>
                  );
                })
              )}
            </div>

            {/* Bottom Actions */}
            <div className="pt-4 border-t border-white/5 flex items-center justify-between shrink-0">
              <span className="text-[11px] text-white/30 font-mono">
                Showing top {previewSamples.length} samples
              </span>

              <div className="flex items-center gap-3">
                <button
                  onClick={() => setPreviewDataset(null)}
                  className="px-4 py-2 rounded-xl text-xs font-bold text-white/50 hover:text-white"
                >
                  Close
                </button>

                <button
                  onClick={() => {
                    const id = previewDataset.id;
                    setPreviewDataset(null);
                    onDistillComplete?.(id);
                  }}
                  className="px-5 py-2 rounded-xl bg-gradient-to-r from-indigo-500 to-purple-600 hover:from-indigo-400 hover:to-purple-500 text-white font-bold text-xs flex items-center gap-2 shadow-lg shadow-indigo-900/30 cursor-pointer"
                >
                  <Zap size={14} />
                  <span>Fine-Tune with this Dataset</span>
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* ------------------------------------------------------------- */}
      {/* MODAL 3: Distill into Alpaca Modal */}
      {/* ------------------------------------------------------------- */}
      {distillTarget && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-in fade-in duration-200">
          <div className="w-full max-w-md bg-[#140F1D] border border-purple-500/20 rounded-3xl p-6 space-y-6 shadow-2xl">
            <div className="flex items-center justify-between border-b border-white/5 pb-3">
              <div className="flex items-center gap-2">
                <Sparkles size={18} className="text-purple-400" />
                <h3 className="text-sm font-bold text-white">Distill into Fine-Tuning JSONL</h3>
              </div>
              <button
                onClick={() => setDistillTarget(null)}
                className="p-1 text-white/40 hover:text-white rounded-lg hover:bg-white/5"
              >
                <X size={16} />
              </button>
            </div>

            <div className="space-y-4">
              <div>
                <span className="text-[10px] font-bold text-white/40 uppercase tracking-widest block mb-1">
                  Source Collection / Text
                </span>
                <div className="p-3 bg-[#0B090F] rounded-xl border border-white/10 text-xs font-bold text-white">
                  {distillTarget.display_name}
                </div>
              </div>

              <div>
                <label className="text-[10px] font-bold text-purple-300 uppercase tracking-widest block mb-1.5">
                  Target Persona & Domain
                </label>
                <input
                  type="text"
                  value={distillPersona}
                  onChange={(e) => setDistillPersona(e.target.value)}
                  placeholder="e.g. Clinical Radiologist & Medical Specialist"
                  className="w-full bg-[#0B090F] border border-white/10 rounded-xl px-4 py-2 text-xs text-white focus:outline-none focus:border-purple-500"
                />
              </div>
            </div>

            <div className="flex items-center justify-end gap-2 pt-2">
              <button
                onClick={() => setDistillTarget(null)}
                className="px-4 py-2 rounded-xl text-xs font-bold text-white/50 hover:text-white"
              >
                Cancel
              </button>
              <button
                onClick={handleStartDistill}
                className="px-5 py-2 rounded-xl bg-purple-600 hover:bg-purple-500 text-white font-bold text-xs flex items-center gap-1.5 shadow-lg shadow-purple-900/30"
              >
                <Sparkles size={13} />
                <span>Launch Distillation</span>
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ------------------------------------------------------------- */}
      {/* MODAL 4: Delete Confirmation Modal */}
      {/* ------------------------------------------------------------- */}
      {itemToDelete && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-in fade-in duration-200">
          <div className="w-full max-w-sm bg-[#140F1D] border border-rose-500/20 rounded-3xl p-6 space-y-5 shadow-2xl">
            <div className="flex items-center gap-3 text-rose-400">
              <AlertCircle size={22} />
              <h3 className="text-sm font-bold text-white">Delete Dataset?</h3>
            </div>
            <p className="text-xs text-white/50 leading-relaxed">
              Are you sure you want to permanently delete <span className="text-white font-bold">'{itemToDelete.name}'</span>? This action cannot be undone.
            </p>
            <div className="flex items-center justify-end gap-2 pt-2">
              <button
                onClick={() => setItemToDelete(null)}
                className="px-4 py-2 rounded-xl text-xs font-bold text-white/50 hover:text-white"
              >
                Cancel
              </button>
              <button
                disabled={isDeleting}
                onClick={handleExecuteDelete}
                className="px-5 py-2 rounded-xl bg-rose-600 hover:bg-rose-500 text-white font-bold text-xs flex items-center gap-1.5 shadow-lg shadow-rose-900/30 disabled:opacity-50"
              >
                {isDeleting ? <Loader2 size={13} className="animate-spin" /> : <Trash2 size={13} />}
                <span>{isDeleting ? "Deleting..." : "Delete Permanently"}</span>
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
